packages:
  - playground
  - crates/relune-render-html

catalog:
  esbuild: 0.28.0
  oxfmt: 0.43.0
  oxlint: 1.58.0
  "@typescript/native-preview": 7.0.0-dev.20260406.1

blockExoticSubdeps: true
minimumReleaseAge: 10080
strictDepBuilds: true
trustPolicy: no-downgrade

onlyBuiltDependencies:
  - esbuild
